package br.unb.mobileMedia.core.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import br.unb.mobileMedia.core.db.AlbumDao;
import br.unb.mobileMedia.core.db.AudioDao;
import br.unb.mobileMedia.core.db.AuthorDao;
import br.unb.mobileMedia.core.db.HistoryDao;
import br.unb.mobileMedia.core.db.PlaylistDao;
import br.unb.mobileMedia.core.db.PlaylistMediaDao;
import br.unb.mobileMedia.core.db.VideoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        AuthorDao.createTable(db, ifNotExists);
        AlbumDao.createTable(db, ifNotExists);
        AudioDao.createTable(db, ifNotExists);
        VideoDao.createTable(db, ifNotExists);
        HistoryDao.createTable(db, ifNotExists);
        PlaylistMediaDao.createTable(db, ifNotExists);
        PlaylistDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        AuthorDao.dropTable(db, ifExists);
        AlbumDao.dropTable(db, ifExists);
        AudioDao.dropTable(db, ifExists);
        VideoDao.dropTable(db, ifExists);
        HistoryDao.dropTable(db, ifExists);
        PlaylistMediaDao.dropTable(db, ifExists);
        PlaylistDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(AuthorDao.class);
        registerDaoClass(AlbumDao.class);
        registerDaoClass(AudioDao.class);
        registerDaoClass(VideoDao.class);
        registerDaoClass(HistoryDao.class);
        registerDaoClass(PlaylistMediaDao.class);
        registerDaoClass(PlaylistDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
