package br.unb.mobileMedia.core.db;

public interface DBConstants {
	public String DATABASE_NAME = "MMUnBDB";
	public int DATABASE_VERSION = 16;

	public String DROP_TABLE_STATEMENTS[] = { "DROP TABLE IF EXISTS AUTHOR",
			"DROP TABLE IF EXISTS AUDIO", "DROP TABLE IF EXISTS EXECUTION_HISTORY" };

	public String CREATE_TABLE_STATEMENTS[] = {
			"CREATE TABLE AUTHOR(" + "PK INTEGER PRIMARY KEY AUTOINCREMENT, "
					+ "ID INTEGER, " + "NAME VARCHAR(50) NOT NULL);",
			
			//TODO: here, we are only considering audio. we must generalize!
			"CREATE TABLE AUDIO ( " + "PK INTEGER PRIMARY KEY AUTOINCREMENT, "
					+ "ID INTEGER, " + "TITLE VARCHAR(50) NOT NULL,"
					+ "URL VARCHAR(255) NOT NULL, " + "ALBUM VARCHAR(50),"
					+ "FK_AUTHOR INTEGER);",

			"CREATE TABLE EXECUTION_HISTORY ( "
					+ "PK INTEGER PRIMARY KEY AUTOINCREMENT, "
					+ "DATE_TIME_EXECUTION CHAR(14), " + "FK_MEDIA INTEGER);" };

	public String SELECT_AUTHORS = "SELECT PK, ID, NAME FROM AUTHOR";
	public String SELECT_AUTHORS_BY_ID = "SELECT PK, ID, NAME FROM AUTHOR WHERE ID = ?";
	public String SELECT_AUTHORS_BY_NAME = "SELECT PK, ID, NAME FROM AUTHOR WHERE NAME = ?";
	public String SELECT_AUDIO_PRODUCTION_BY_AUTHOR_KEY = "SELECT PK, ID, TITLE, ALBUM, URL FROM AUDIO WHERE FK_AUTHOR = ?";
	public String SELECT_AUDIO_BY_AUTHOR_KEY_TITLE = "SELECT PK, ID FROM AUDIO WHERE FK_AUTHOR = ? AND TITLE = ?";
	public String LIST_AUDIO_PRODUCTION = "SELECT PK, ID, TITLE, ALBUM, URL FROM AUDIO";
	
	public String SELECT_EXECUTION_HISTORY = 
			"SELECT A.PK, A.ID, A.TITLE, A.ALBUM, A.URL, EH.DATE_TIME_EXECUTION " +
			"FROM AUDIO A INNER JOIN EXECUTION_HISTORY EH " +
			" ON A.PK = EH.FK_MEDIA " +
			"WHERE DATE_TIME_EXECUTION < ? AND DATE_TIME_EXECUTION > ?";
	
	
	public String AUTHOR_TABLE = "AUTHOR";
	public String AUTHOR_KEY_COLUMN = "PK";
	public String AUTHOR_ID_COLUMN = "ID";
	public String AUTHOR_NAME_COLUMN = "NAME";

	public String AUDIO_TABLE = "AUDIO";
	public String AUDIO_KEY_COLUMN = "PK";
	public String AUDIO_ID_COLUMN = "ID";
	public String AUDIO_TITLE_COLUMN = "TITLE";
	public String AUDIO_ALBUM_COLUMN = "ALBUM";
	public String AUDIO_URL_COLUMN = "URL";
	public String AUDIO_FK_AUTHOR_COLUMN = "FK_AUTHOR";
	
	public String EH_TABLE = "EXECUTION_HISTORY";
	public String EH_DATE_TIME_EXECUTION_COLUMN = "DATE_TIME_EXECUTION"; 
	public String EH_FK_AUDIO_COLUMN = "FK_MEDIA";


}
