//package br.unb.mobileMedia.core.db;
//
//import android.database.Cursor;
//import android.database.sqlite.SQLiteDatabase;
//import android.database.sqlite.SQLiteStatement;
//import br.unb.mobileMedia.core.domain.Video;
//import de.greenrobot.dao.AbstractDao;
//import de.greenrobot.dao.Property;
//import de.greenrobot.dao.internal.DaoConfig;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
///** 
// * DAO for table VIDEO.
//*/
//public class VideoDao extends AbstractDao<Video, Long> {
//
//    public static final String TABLENAME = "VIDEO";
//
//    /**
//     * Properties of entity Video.<br/>
//     * Can be used for QueryBuilder and for referencing column names.
//    */
//    public static class Properties {
//        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
//        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
//        public final static Property Url = new Property(2, String.class, "url", false, "URL");
//    };
//
//    private DaoSession daoSession;
//
//
//    public VideoDao(DaoConfig config) {
//        super(config);
//    }
//    
//    public VideoDao(DaoConfig config, DaoSession daoSession) {
//        super(config, daoSession);
//        this.daoSession = daoSession;
//    }
//
//    /** Creates the underlying database table. */
//    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
//        String constraint = ifNotExists? "IF NOT EXISTS ": "";
//        db.execSQL("CREATE TABLE " + constraint + "'VIDEO' (" + //
//                "'_id' INTEGER PRIMARY KEY ," + // 0: id
//                "'TITLE' TEXT," + // 1: title
//                "'URL' TEXT);"); // 2: url
//    }
//
//    /** Drops the underlying database table. */
//    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
//        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'VIDEO'";
//        db.execSQL(sql);
//    }
//
//    /** @inheritdoc */
//    @Override
//    protected void bindValues(SQLiteStatement stmt, Video entity) {
//        stmt.clearBindings();
// 
//        Long id = entity.getId();
//        if (id != null) {
//            stmt.bindLong(1, id);
//        }
// 
//        String title = entity.getTitle();
//        if (title != null) {
//            stmt.bindString(2, title);
//        }
// 
//        String url = entity.getUrl();
//        if (url != null) {
//            stmt.bindString(3, url);
//        }
//    }
//
//    @Override
//    protected void attachEntity(Video entity) {
//        super.attachEntity(entity);
//        entity.__setDaoSession(daoSession);
//    }
//
//    /** @inheritdoc */
//    @Override
//    public Long readKey(Cursor cursor, int offset) {
//        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
//    }    
//
//    /** @inheritdoc */
//    @Override
//    public Video readEntity(Cursor cursor, int offset) {
//        Video entity = new Video( //
//            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
//            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
//            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // url
//        );
//        return entity;
//    }
//     
//    /** @inheritdoc */
//    @Override
//    public void readEntity(Cursor cursor, Video entity, int offset) {
//        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
//        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
//        entity.setUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
//     }
//    
//    /** @inheritdoc */
//    @Override
//    protected Long updateKeyAfterInsert(Video entity, long rowId) {
//        entity.setId(rowId);
//        return rowId;
//    }
//    
//    /** @inheritdoc */
//    @Override
//    public Long getKey(Video entity) {
//        if(entity != null) {
//            return entity.getId();
//        } else {
//            return null;
//        }
//    }
//
//    /** @inheritdoc */
//    @Override    
//    protected boolean isEntityUpdateable() {
//        return true;
//    }
//    
//}
