package br.unb.mobileMedia.core.db.dao;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import br.unb.mobileMedia.core.db.idao.PlaylistMediaDao;
import br.unb.mobileMedia.core.domain.Album;
import br.unb.mobileMedia.core.domain.Audio;
import br.unb.mobileMedia.core.domain.Author;
import br.unb.mobileMedia.core.domain.History;
import br.unb.mobileMedia.core.domain.Playlist;
import br.unb.mobileMedia.core.domain.PlaylistMedia;
import br.unb.mobileMedia.core.domain.Video;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig authorDaoConfig;
    private final DaoConfig albumDaoConfig;
    private final DaoConfig audioDaoConfig;
    private final DaoConfig videoDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig playlistMediaDaoConfig;
    private final DaoConfig playlistDaoConfig;

    private final AuthorDao authorDao;
    private final AlbumDao albumDao;
    private final AudioDao audioDao;
    private final VideoDao videoDao;
    private final HistoryDao historyDao;
    private final PlaylistMediaDao playlistMediaDao;
    private final PlaylistDao playlistDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        authorDaoConfig = daoConfigMap.get(AuthorDao.class).clone();
        authorDaoConfig.initIdentityScope(type);

        albumDaoConfig = daoConfigMap.get(AlbumDao.class).clone();
        albumDaoConfig.initIdentityScope(type);

        audioDaoConfig = daoConfigMap.get(AudioDao.class).clone();
        audioDaoConfig.initIdentityScope(type);

        videoDaoConfig = daoConfigMap.get(VideoDao.class).clone();
        videoDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        playlistMediaDaoConfig = daoConfigMap.get(PlaylistMediaDao.class).clone();
        playlistMediaDaoConfig.initIdentityScope(type);

        playlistDaoConfig = daoConfigMap.get(PlaylistDao.class).clone();
        playlistDaoConfig.initIdentityScope(type);

        authorDao = new AuthorDao(authorDaoConfig, this);
        albumDao = new AlbumDao(albumDaoConfig, this);
        audioDao = new AudioDao(audioDaoConfig, this);
        videoDao = new VideoDao(videoDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        playlistMediaDao = new PlaylistMediaDao(playlistMediaDaoConfig, this);
        playlistDao = new PlaylistDao(playlistDaoConfig, this);

        registerDao(Author.class, authorDao);
        registerDao(Album.class, albumDao);
        registerDao(Audio.class, audioDao);
        registerDao(Video.class, videoDao);
        registerDao(History.class, historyDao);
        registerDao(PlaylistMedia.class, playlistMediaDao);
        registerDao(Playlist.class, playlistDao);
    }
    
    public void clear() {
        authorDaoConfig.getIdentityScope().clear();
        albumDaoConfig.getIdentityScope().clear();
        audioDaoConfig.getIdentityScope().clear();
        videoDaoConfig.getIdentityScope().clear();
        historyDaoConfig.getIdentityScope().clear();
        playlistMediaDaoConfig.getIdentityScope().clear();
        playlistDaoConfig.getIdentityScope().clear();
    }

    public AuthorDao getAuthorDao() {
        return authorDao;
    }

    public AlbumDao getAlbumDao() {
        return albumDao;
    }

    public AudioDao getAudioDao() {
        return audioDao;
    }

    public VideoDao getVideoDao() {
        return videoDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public PlaylistMediaDao getPlaylistMediaDao() {
        return playlistMediaDao;
    }

    public PlaylistDao getPlaylistDao() {
        return playlistDao;
    }

}
